
skillMetadata:
  sections:
    - name: payment_details
      fields:
        - name: ccnum
          type: text
          label: credit card number
          value: "5123456789012346"

        - name: ccname
          type: text
          label: credit card name
          value: "karan"

        - name: ccvv
          type: text
          label: credit card CVV
          value: "123"

        - name: ccexpmon
          type: text
          label: credit card exp month
          value: "05"

        - name: ccexpyr
          type: text
          label: credit card number
          value: "2020"


        - name: pg
          type: text
          label: credit card number
          value: "CC"

        - name: bankcode
          type: text
          label: credit card number
          value: "CC"

        
    - name: Login << Name of another section
      fields:
        - type: label
          label: Just a little bit of extra info for the user to understand following settings
        - name: username
          type: text
          label: Username
          value: ""
        - name: password
          type: password
          label: Password
          value: ""
